name: Exécutable dotnet

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Mise en place de dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/departement-info-cem/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Installer les dépendances
        working-directory: ./scriptsharp
        run: dotnet restore
      - run: dotnet publish --configuration Release -r win-x64 -p:PublishSingleFile=true --self-contained true
        working-directory: ./scriptsharp
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ScriptSharp/bin/Release/net8.0/win-x64/publish/ScriptSharp.exe