name: dotnet executable

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Mise en place de dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/departement-info-cem/index.json
      - name: Installer les dépendances
        working-directory: ./scriptsharp
        run: dotnet restore
      - run: dotnet build --configuration Release ScriptSharp
        working-directory: ./scriptsharp
      - name: Créer le package
        working-directory: ./scriptsharp
        run: dotnet pack --configuration Release ScriptSharp
      - name: Publier le package vers GitHub Package Registry (GPR)
        working-directory: ./scriptsharp
        run: dotnet nuget push ScriptSharp\bin\Release\*.nupkg --api-key ${{secrets.GITHUB_TOKEN }} --skip-duplicate